### ISSUE TITLE
OperationalError: relation already exists in schema "public_immune"

### ISSUE THREAD

**Issue by droserasprout** [dipdup-net/dipdup-py#460]
https://sentry.io/share/issue/21b7349157024b048bc69fe37f55b915/

**Comment by Anshit01** [comment]
Figured out the database had both public and public_immune schema visible on data tab on hasura, ipfs table existed in both the schema, I deleted the public_immune schema from hasura and schema wipe command worked.

My best guess is that the public_immune schema was left in an older failed schema wipe command. I use docker so, to wipe the schema, I start the container with schema wipe command instead of run command. The service is configured to auto-restart, so it keeps wiping the schema in an infinite loop untill I restart the container with docker run command. So, sometimes it exits right after moving ipfs to public_immune.

Probably not the best way to do it. So I'm now using docker exec command to wipe the schema.

You can probably ignore this issue, but if it's possible, wrapping it in a sql transaction will be better.

**Comment by droserasprout** [comment]
Thanks for the detailed report! Wrapping stuff in transactions is (almost) always a good idea. Fix is on the way.

It would be nice to have a way to inform the running DipDup instance to reindex without stopping the container, but it's not possible atm. So yeah, for now, `docker exec` is the best option. Or, if you're in a playful mood, `SELECT truncate_schema('public');` 😈
